# Generated by Django 4.2.4 on 2023-10-17 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='动漫名')),
                ('other_name', models.CharField(max_length=256, verbose_name='其他名字')),
                ('store_number', models.PositiveIntegerField(default=None, null=True, unique=True, verbose_name='存贮号')),
                ('released_time', models.CharField(max_length=32, null=True, verbose_name='上映时间')),
                ('language', models.CharField(max_length=8, null=True, verbose_name='语言')),
                ('auther', models.CharField(max_length=32, null=True, verbose_name='作者')),
                ('status', models.BooleanField(default=False, verbose_name='连载状态')),
                ('region', models.CharField(max_length=16, verbose_name='地区')),
                ('image', models.CharField(max_length=1024, verbose_name='图片')),
                ('ani_url', models.URLField(default=None, null=True, verbose_name='视频详情页链接')),
                ('introduction', models.TextField(max_length=1024, verbose_name='简介')),
            ],
            options={
                'verbose_name': '动漫详情表',
                'verbose_name_plural': '动漫详情表',
            },
        ),
        migrations.CreateModel(
            name='week_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('0', '不是更新'), ('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五'), ('6', '星期六'), ('7', '星期日')], max_length=64, unique=True, verbose_name='星期')),
            ],
            options={
                'verbose_name': '周更表tags',
                'verbose_name_plural': '周更表tags',
            },
        ),
        migrations.CreateModel(
            name='Anime_episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_num', models.IntegerField(verbose_name='来源的储存号')),
                ('episode', models.CharField(max_length=16, verbose_name='集数')),
                ('episode_url', models.CharField(max_length=516, verbose_name='视频地址')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_detail', to='anime_func.anime_detail', verbose_name='外键链接')),
            ],
            options={
                'verbose_name': '动漫集数表',
                'verbose_name_plural': '动漫集数表',
            },
        ),
        migrations.AddField(
            model_name='anime_detail',
            name='link_week',
            field=models.ManyToManyField(related_name='animes', to='anime_func.week_tags'),
        ),
    ]
