# Generated by Django 4.2.4 on 2023-10-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_func', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime_detail',
            name='status',
            field=models.BooleanField(default=False, verbose_name='连载状态'),
        ),
        migrations.AlterField(
            model_name='anime_detail',
            name='store_number',
            field=models.PositiveIntegerField(default=None, null=True, unique=True, verbose_name='存贮号'),
        ),
    ]
