# Generated by Django 4.2.4 on 2023-10-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_func', '0002_week_tags_anime_detail_link_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week_tags',
            options={'verbose_name': '周更表tags', 'verbose_name_plural': '周更表tags'},
        ),
        migrations.AlterField(
            model_name='anime_detail',
            name='link_week',
            field=models.ManyToManyField(null=True, related_name='animes', to='anime_func.week_tags'),
        ),
        migrations.AlterField(
            model_name='week_tags',
            name='week',
            field=models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五'), ('6', '星期六'), ('7', '星期日')], max_length=64, unique=True, verbose_name='星期'),
        ),
    ]
