# Generated by Django 4.2.4 on 2023-10-25 03:08

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='记录mysql时间')),
                ('error_type', models.CharField(choices=[('1', '动漫类型错误')], max_length=64, verbose_name='错误类型')),
                ('error_content', models.TextField()),
            ],
            options={
                'verbose_name': '错误表',
                'verbose_name_plural': '错误表',
            },
        ),
        migrations.CreateModel(
            name='my_bolgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('1', '爬虫'), ('2', 'django'), ('3', '前端'), ('4', 'mysql')], max_length=16, null=True, verbose_name='分类')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='博客名字')),
                ('introduction', models.TextField(default=None, max_length=256, null=True, verbose_name='简介')),
                ('content', mdeditor.fields.MDTextField()),
                ('date', models.DateTimeField(auto_now=True, verbose_name='更新实践')),
            ],
            options={
                'verbose_name': '博客表',
                'verbose_name_plural': '博客表',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('telephone', models.BigIntegerField(null=True, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('user_image', models.ImageField(upload_to='', verbose_name='用户图片')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
    ]
