# Generated by Django 4.2.4 on 2023-10-25 04:01

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stationmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_bolgs',
            name='content',
            field=mdeditor.fields.MDTextField(default=None, null=True, verbose_name='博客内容'),
        ),
    ]
