# Generated by Django 4.2.4 on 2023-10-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_bolgs',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新实践'),
        ),
        migrations.AddField(
            model_name='my_bolgs',
            name='introduction',
            field=models.TextField(default=None, max_length=256, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='my_bolgs',
            name='classification',
            field=models.CharField(choices=[('1', '爬虫'), ('2', 'django'), ('3', '前端'), ('4', 'mysql')], max_length=16, null=True, verbose_name='分类'),
        ),
    ]
