# Generated by Django 4.2.4 on 2023-09-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='动漫名')),
                ('store_number', models.PositiveIntegerField(unique=True, verbose_name='存贮号')),
                ('released_time', models.CharField(max_length=32, null=True, verbose_name='上映时间')),
                ('language', models.CharField(max_length=8, null=True, verbose_name='语言')),
                ('auther', models.CharField(max_length=32, null=True, verbose_name='作者')),
                ('status', models.BooleanField(verbose_name='连载状态')),
                ('region', models.CharField(max_length=16, verbose_name='地区')),
                ('image', models.CharField(max_length=1024, verbose_name='图片')),
                ('ani_url', models.URLField(default=None, null=True, verbose_name='视频详情页链接')),
                ('introduction', models.TextField(max_length=256, verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='频道名称')),
                ('sign', models.CharField(max_length=64, verbose_name='简述')),
                ('auther', models.CharField(max_length=16, verbose_name='作者')),
                ('subscribe', models.BigIntegerField(verbose_name='订阅')),
                ('image', models.ImageField(upload_to='', verbose_name='频道图片')),
                ('seq_num', models.BigIntegerField(verbose_name='序列号')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='管理员')),
                ('password', models.CharField(max_length=64, unique=True, verbose_name='管理员密码')),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='合集名称')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Collections', to='manage_func.channel', verbose_name='外键链接频道')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='文章名')),
                ('auther', models.CharField(max_length=16, verbose_name='作者')),
                ('up_time', models.DateTimeField(verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='manage_func.collections', verbose_name='外键链接合集')),
            ],
        ),
        migrations.CreateModel(
            name='Anime_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='资源来源')),
                ('source_num', models.IntegerField(verbose_name='源的号')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Anime_source', to='manage_func.anime_detail', verbose_name='外键链接')),
            ],
        ),
        migrations.CreateModel(
            name='Anime_episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.CharField(max_length=16, verbose_name='集数')),
                ('episode_url', models.CharField(max_length=516, verbose_name='视频地址')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_detail', to='manage_func.anime_source', verbose_name='外键链接')),
            ],
        ),
    ]
