# Generated by Django 4.2.4 on 2023-10-14 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='频道名称')),
                ('sign', models.CharField(max_length=64, verbose_name='简述')),
                ('auther', models.CharField(max_length=16, verbose_name='作者')),
                ('subscribe', models.BigIntegerField(verbose_name='订阅')),
                ('image', models.ImageField(upload_to='static/img', verbose_name='频道图片')),
                ('seq_num', models.BigIntegerField(unique=True, verbose_name='序列号')),
            ],
            options={
                'verbose_name': '频道表',
                'verbose_name_plural': '频道表',
            },
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='合集名称')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Collections', to='forum_func.channel', verbose_name='外键链接频道')),
            ],
            options={
                'verbose_name': '合集表',
                'verbose_name_plural': '合集表',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='文章名')),
                ('auther', models.CharField(max_length=16, verbose_name='作者')),
                ('up_time', models.DateTimeField(verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='forum_func.collections', verbose_name='外键链接合集')),
            ],
            options={
                'verbose_name': '博客表',
                'verbose_name_plural': '博客表',
            },
        ),
    ]
